#!/usr/bin/env bash
# Copyright ScyllaDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

[[ $# -eq 0 ]] || {
    echo "usage: $0" >&2
    exit 2
}

for command in jq shasum tar; do
    command -v "$command" >/dev/null || {
        echo "$command is required to run candidate-mode tests" >&2
        exit 1
    }
done

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
verifier=$script_dir/verify-candidate.sh
publisher=$script_dir/publish-and-verify.sh
finalizer=$script_dir/finalize-release.sh
evidence_generator=$script_dir/create-evidence.sh
test_dir=$(mktemp -d)
trap 'rm -rf -- "$test_dir"' EXIT

version=9.8.7
other_version=9.8.8
commit=0123456789abcdef0123456789abcdef01234567
other_commit=abcdef0123456789abcdef0123456789abcdef01
run_id=24680
release_candidate="v$version-rc.3"
other_release_candidate="v$version-rc.4"
validation_candidate="validation-$run_id"
other_validation_candidate=validation-24681
rust_pin=1.94.1
rustdoc_pin=nightly-2026-06-23
ccm_pin=f9e8f8c221f76251318c61ba8a0ce6acec860f6d
scylla_versions=$(bash "$script_dir/release-policy.sh" scylla-versions)
export RUST_VERSION=$rust_pin
export RUSTDOC_TOOLCHAIN=$rustdoc_pin
export CCM_COMMIT=$ccm_pin

sha256() {
    shasum -a 256 "$1" | awk '{ print $1 }'
}

refresh_checksums() {
    local candidate_dir=$1
    local crate_file
    local sbom_file

    crate_file=$(jq -er '.crate.file' "$candidate_dir/release-manifest.json")
    sbom_file=$(jq -er '.sbom.file' "$candidate_dir/release-manifest.json")
    (
        cd "$candidate_dir"
        shasum -a 256 "$crate_file" "$sbom_file" release-manifest.json >SHA256SUMS
    )
}

write_candidate() {
    local candidate_dir=$1
    local release_mode=$2
    local candidate_id=$3
    local workflow_run_id=$4
    local rc_tag_json=$5
    local stage=$test_dir/stage-${candidate_dir##*/}
    local root=alternator-client-$version
    local package_dir=$stage/$root
    local crate_file=alternator-client-$version.crate
    local sbom_file=alternator-client-$version.cdx.json
    local crate_sha
    local sbom_sha
    local cargo_lock_sha
    local changelog_sha

    mkdir -p "$candidate_dir" "$package_dir"
    printf '%s\n' \
        '[package]' \
        'name = "alternator-client"' \
        "version = \"$version\"" \
        'edition = "2021"' >"$package_dir/Cargo.toml"
    printf '%s\n' \
        '# This file is automatically @generated by Cargo.' \
        'version = 3' \
        '' \
        '[[package]]' \
        'name = "alternator-client"' \
        "version = \"$version\"" >"$package_dir/Cargo.lock"
    printf '# Changelog\n\n## [%s] - 2026-10-02\n\nSynthetic test release.\n' \
        "$version" >"$package_dir/CHANGELOG.md"
    jq -n --arg commit "$commit" \
        '{git: {sha1: $commit}, path_in_vcs: ""}' >"$package_dir/.cargo_vcs_info.json"

    tar -czf "$candidate_dir/$crate_file" -C "$stage" "$root"
    printf '%s\n' \
        '{"bomFormat":"CycloneDX","specVersion":"1.6","components":[]}' \
        >"$candidate_dir/$sbom_file"

    crate_sha=$(sha256 "$candidate_dir/$crate_file")
    sbom_sha=$(sha256 "$candidate_dir/$sbom_file")
    cargo_lock_sha=$(sha256 "$package_dir/Cargo.lock")
    changelog_sha=$(sha256 "$package_dir/CHANGELOG.md")
    jq -n \
        --arg release_mode "$release_mode" \
        --arg candidate_id "$candidate_id" \
        --arg version "$version" \
        --arg crate_file "$crate_file" \
        --arg crate_sha "$crate_sha" \
        --arg sbom_file "$sbom_file" \
        --arg sbom_sha "$sbom_sha" \
        --arg commit "$commit" \
        --arg workflow_run_id "$workflow_run_id" \
        --arg rust_pin "$rust_pin" \
        --arg rustdoc_pin "$rustdoc_pin" \
        --arg ccm_pin "$ccm_pin" \
        --arg cargo_lock_sha "$cargo_lock_sha" \
        --arg changelog_sha "$changelog_sha" \
        --argjson rc_tag "$rc_tag_json" \
        --argjson scylla_versions "$scylla_versions" '
        {
            schema_version: 2,
            release_mode: $release_mode,
            candidate_id: $candidate_id,
            crate: {
                name: "alternator-client",
                library_name: "alternator_driver",
                version: $version,
                file: $crate_file,
                sha256: $crate_sha
            },
            rc_tag: $rc_tag,
            commit_sha: $commit,
            workflow_run_id: $workflow_run_id,
            toolchains: {
                rust: {pin: $rust_pin, actual: "rustc synthetic-test"},
                rustdoc: {pin: $rustdoc_pin, actual: "rustdoc synthetic-test"}
            },
            ccm_commit: $ccm_pin,
            scylla_versions: $scylla_versions,
            cargo_lock_sha256: $cargo_lock_sha,
            changelog_sha256: $changelog_sha,
            source_date_epoch: "1790899200",
            sbom: {file: $sbom_file, sha256: $sbom_sha}
        }
    ' >"$candidate_dir/release-manifest.json"
    refresh_checksums "$candidate_dir"
}

release_dir=$test_dir/release
validation_dir=$test_dir/validation
release_rc_json=$(jq -cn --arg rc "$release_candidate" '$rc')
write_candidate "$release_dir" release "$release_candidate" "$run_id" "$release_rc_json"
write_candidate "$validation_dir" validate "$validation_candidate" "$run_id" null
mkdir "$test_dir/extract"

test_count=0
last_status=0
last_output=

run_verifier() {
    local output_file=$test_dir/verifier-output

    set +e
    "$verifier" "$@" >"$output_file" 2>&1
    last_status=$?
    set -e
    last_output=$(<"$output_file")
}

expect_verify_success() {
    local label=$1
    shift

    run_verifier "$@"
    [[ "$last_status" -eq 0 ]] || {
        echo "$label: expected verification success, got status $last_status" >&2
        echo "$last_output" >&2
        exit 1
    }
    test_count=$((test_count + 1))
}

expect_verify_failure() {
    local label=$1
    local diagnostic=$2
    shift 2

    run_verifier "$@"
    [[ "$last_status" -ne 0 ]] || {
        echo "$label: expected verification failure" >&2
        echo "$last_output" >&2
        exit 1
    }
    [[ "$last_output" == *"$diagnostic"* ]] || {
        echo "$label: missing diagnostic: $diagnostic" >&2
        echo "$last_output" >&2
        exit 1
    }
    test_count=$((test_count + 1))
}

expect_verify_success valid_release \
    "$release_dir" "$test_dir/extract" release "$version" "$release_candidate" "$commit"
expect_verify_success valid_validation \
    "$validation_dir" "$test_dir/extract" validate "$version" "$validation_candidate" "$commit"

expect_verify_failure missing_all_identity_arguments 'usage:' \
    "$release_dir" "$test_dir/extract"
[[ "$last_status" -eq 2 ]] || {
    echo "missing_all_identity_arguments: expected usage status 2, got $last_status" >&2
    exit 1
}
expect_verify_failure missing_expected_commit 'usage:' \
    "$release_dir" "$test_dir/extract" release "$version" "$release_candidate"
[[ "$last_status" -eq 2 ]] || {
    echo "missing_expected_commit: expected usage status 2, got $last_status" >&2
    exit 1
}
expect_verify_failure wrong_expected_mode 'invalid expected release mode: preview' \
    "$release_dir" "$test_dir/extract" preview "$version" "$release_candidate" "$commit"
expect_verify_failure wrong_expected_version "manifest version $version does not match expected version $other_version" \
    "$release_dir" "$test_dir/extract" release "$other_version" "v$other_version-rc.3" "$commit"
expect_verify_failure malformed_expected_candidate 'invalid expected release candidate ID' \
    "$release_dir" "$test_dir/extract" release "$version" "$validation_candidate" "$commit"
expect_verify_failure wrong_expected_candidate \
    "manifest candidate ID $release_candidate does not match expected ID $other_release_candidate" \
    "$release_dir" "$test_dir/extract" release "$version" "$other_release_candidate" "$commit"
expect_verify_failure wrong_expected_commit \
    "manifest commit $commit does not match expected commit $other_commit" \
    "$release_dir" "$test_dir/extract" release "$version" "$release_candidate" "$other_commit"

expect_verify_failure release_artifact_as_validation \
    'manifest mode release does not match expected mode validate' \
    "$release_dir" "$test_dir/extract" validate "$version" "$validation_candidate" "$commit"
expect_verify_failure validation_artifact_as_release \
    'manifest mode validate does not match expected mode release' \
    "$validation_dir" "$test_dir/extract" release "$version" "$release_candidate" "$commit"
expect_verify_failure wrong_validation_candidate \
    "manifest candidate ID $validation_candidate does not match expected ID $other_validation_candidate" \
    "$validation_dir" "$test_dir/extract" validate "$version" "$other_validation_candidate" "$commit"

bad_release_rc_dir=$test_dir/bad-release-rc
cp -R "$release_dir" "$bad_release_rc_dir"
jq --arg rc "$other_release_candidate" '.rc_tag = $rc' \
    "$bad_release_rc_dir/release-manifest.json" >"$test_dir/manifest.tmp"
mv "$test_dir/manifest.tmp" "$bad_release_rc_dir/release-manifest.json"
refresh_checksums "$bad_release_rc_dir"
expect_verify_failure release_rc_identity_mismatch \
    "release manifest RC tag must equal candidate ID $release_candidate" \
    "$bad_release_rc_dir" "$test_dir/extract" release "$version" "$release_candidate" "$commit"

bad_validation_rc_dir=$test_dir/bad-validation-rc
cp -R "$validation_dir" "$bad_validation_rc_dir"
jq --arg rc "$release_candidate" '.rc_tag = $rc' \
    "$bad_validation_rc_dir/release-manifest.json" >"$test_dir/manifest.tmp"
mv "$test_dir/manifest.tmp" "$bad_validation_rc_dir/release-manifest.json"
refresh_checksums "$bad_validation_rc_dir"
expect_verify_failure validation_rc_not_null \
    'validation manifest RC tag must be null' \
    "$bad_validation_rc_dir" "$test_dir/extract" validate "$version" "$validation_candidate" "$commit"

bad_validation_run_dir=$test_dir/bad-validation-run
cp -R "$validation_dir" "$bad_validation_run_dir"
jq --arg run_id 24681 '.workflow_run_id = $run_id' \
    "$bad_validation_run_dir/release-manifest.json" >"$test_dir/manifest.tmp"
mv "$test_dir/manifest.tmp" "$bad_validation_run_dir/release-manifest.json"
refresh_checksums "$bad_validation_run_dir"
expect_verify_failure validation_run_identity_mismatch \
    'validation candidate ID does not match manifest workflow run ID' \
    "$bad_validation_run_dir" "$test_dir/extract" validate "$version" "$validation_candidate" "$commit"

evidence_bin=$test_dir/evidence-bin
mkdir "$evidence_bin"
printf '%s\n' \
    '#!/usr/bin/env bash' \
    'set -euo pipefail' \
    '[[ "${1:-}" == api ]] || exit 90' \
    'printf '\''%s\n'\'' '\''[{"jobs":[{"id":123,"name":"Synthetic gate","runner_name":"mock-runner","status":"completed","conclusion":"success","started_at":"2026-10-02T00:00:00Z","completed_at":"2026-10-02T00:00:01Z","html_url":"https://github.example/jobs/123"}]}]'\''' \
    >"$evidence_bin/gh"
chmod 755 "$evidence_bin/gh"
crate_sha=$(jq -er '.crate.sha256' "$release_dir/release-manifest.json")

expect_evidence() {
    local label=$1
    local release_mode=$2
    local candidate_id=$3
    local attestation_result=$4
    local expected_passed=$5
    local output_file=$test_dir/$label.json
    local command_output=$test_dir/$label-output

    set +e
    GITHUB_REPOSITORY=scylladb/alternator-client-rust \
        GITHUB_RUN_ID=$run_id \
        GITHUB_RUN_ATTEMPT=2 \
        GH_TOKEN=test-token \
        PORTABLE_RESULT=success \
        STATIC_RESULT=success \
        SCYLLA_RESULT=success \
        ATTESTATION_RESULT="$attestation_result" \
        PATH="$evidence_bin:$PATH" \
        "$evidence_generator" \
        "$release_mode" "$version" "$candidate_id" "$commit" "$crate_sha" "$output_file" \
        >"$command_output" 2>&1
    last_status=$?
    set -e
    last_output=$(<"$command_output")
    [[ "$last_status" -eq 0 ]] || {
        echo "$label: evidence generation failed with status $last_status" >&2
        echo "$last_output" >&2
        exit 1
    }
    jq -e \
        --arg mode "$release_mode" \
        --arg candidate "$candidate_id" \
        --arg attestation "$attestation_result" \
        --argjson expected_passed "$expected_passed" '
        .schema_version == 2 and
        .release_mode == $mode and
        .candidate_id == $candidate and
        .aggregate_results.attestation == $attestation and
        .aggregate_results.portable == "success" and
        .aggregate_results.static_release == "success" and
        .aggregate_results.scylla == "success" and
        .all_required_gates_passed == $expected_passed and
        (.jobs | length == 1) and
        (if $mode == "release"
         then .rc_tag == $candidate
         else .rc_tag == null
         end)
    ' "$output_file" >/dev/null || {
        echo "$label: generated evidence did not match its mode/gate contract" >&2
        jq . "$output_file" >&2
        exit 1
    }
    test_count=$((test_count + 1))
}

expect_evidence release_attestation_success \
    release "$release_candidate" success true
expect_evidence validation_attestation_skipped \
    validate "$validation_candidate" skipped true
expect_evidence validation_attestation_success \
    validate "$validation_candidate" success false
expect_evidence release_attestation_skipped \
    release "$release_candidate" skipped false

fake_bin=$test_dir/forbidden-bin
mkdir "$fake_bin"
for command in cargo curl gh git; do
    printf '%s\n' \
        '#!/usr/bin/env bash' \
        'set -euo pipefail' \
        'printf '\''%s\n'\'' "${0##*/}" >>"${FORBIDDEN_CALLS:?}"' \
        'exit 97' >"$fake_bin/$command"
    chmod 755 "$fake_bin/$command"
done

expect_validation_guard() {
    local label=$1
    local expected_diagnostic=$2
    local script=$3
    shift 3
    local marker=$test_dir/$label-forbidden-calls
    local output_file=$test_dir/$label-output

    set +e
    PATH="$fake_bin:$PATH" \
        FORBIDDEN_CALLS="$marker" \
        CARGO_REGISTRY_TOKEN= \
        GITHUB_REPOSITORY=scylladb/alternator-client-rust \
        GH_TOKEN= \
        RELEASE_APP_TOKEN= \
        "$script" "$@" >"$output_file" 2>&1
    last_status=$?
    set -e
    last_output=$(<"$output_file")
    [[ "$last_status" -eq 1 ]] || {
        echo "$label: expected mode rejection status 1, got $last_status" >&2
        echo "$last_output" >&2
        exit 1
    }
    [[ "$last_output" == *"$expected_diagnostic"* ]] || {
        echo "$label: missing diagnostic: $expected_diagnostic" >&2
        echo "$last_output" >&2
        exit 1
    }
    [[ ! -e "$marker" ]] || {
        echo "$label: validation artifact reached a credential, network, or mutation command" >&2
        cat "$marker" >&2
        exit 1
    }
    test_count=$((test_count + 1))
}

expect_validation_guard publish_rejects_validation \
    'publish requires release_mode=release' "$publisher" \
    validate "$test_dir/nonexistent-package" "$version" "$validation_candidate" "$commit" "$validation_dir"
expect_validation_guard finalize_rejects_validation \
    'finalization requires release_mode=release' "$finalizer" \
    validate "$version" "$validation_candidate" "$commit" "$validation_dir" "$test_dir/nonexistent-evidence"
expect_validation_guard publish_rejects_relabelled_validation_artifact \
    'manifest mode validate does not match expected mode release' "$publisher" \
    release "$test_dir/nonexistent-package" "$version" "$release_candidate" "$commit" "$validation_dir"
expect_validation_guard finalize_rejects_relabelled_validation_artifact \
    'manifest mode validate does not match expected mode release' "$finalizer" \
    release "$version" "$release_candidate" "$commit" "$validation_dir" "$test_dir/nonexistent-evidence"

echo "$test_count candidate-mode release tests passed"
